spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  devtools:
        livereload:
            enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
handlebars:
  expose-request-attributes: true
  expose-session-attributes: true
