spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  application:
    name: NoticeBoard
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8080/NoticeBoardSpring
    username: root
    password: root
  devtools:
        livereload:
            enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
handlebars:
  expose-request-attributes: true
  expose-session-attributes: true
  
  
