insert into USER (USER_ID, CREATE_DATE, MODIFIED_DATE, USER_EMAIL, USER_FIRSTNAME, USER_PASSWORD, USER_PHONE, USER_SECONDNAME) values ('tjdans174',now(),now(),'tjdans174@naver.com','kang','dkrak174','01041606443','sungmun');
insert into USER (USER_ID, CREATE_DATE, MODIFIED_DATE, USER_EMAIL, USER_FIRSTNAME, USER_PASSWORD, USER_PHONE, USER_SECONDNAME) values ('dkrak174',now(),now(),'dkrak174@daum.net','kang','tjdans174','01041606443','sungmun');
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (1, now(),now(),'TestContents','Test1','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (2, now(),now(),'TestContents','Test2','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (3, now(),now(),'TestContents','Test3','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (4, now(),now(),'TestContents','Test4','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (5, now(),now(),'TestContents','Test5','dkrak174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (6, now(),now(),'TestContents','Test6','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (7, now(),now(),'TestContents','Test7','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (8, now(),now(),'TestContents','Test8','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (9, now(),now(),'TestContents','Test9','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (10, now(),now(),'TestContents','Test10','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (11, now(),now(),'TestContents','Test11','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (12, now(),now(),'TestContents','Test12','dkrak174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (13, now(),now(),'TestContents','Test13','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (14, now(),now(),'TestContents','Test14','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (15, now(),now(),'TestContents','Test15','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (16, now(),now(),'TestContents','Test16','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (17, now(),now(),'TestContents','Test17','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (18, now(),now(),'TestContents','Test18','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (19, now(),now(),'TestContents','Test19','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (20, now(),now(),'TestContents','Test20','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (21, now(),now(),'TestContents','Test21','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (22, now(),now(),'TestContents','Test22','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (23, now(),now(),'TestContents','Test23','dkrak174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (24, now(),now(),'TestContents','Test24','tjdans174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (25, now(),now(),'TestContents','Test25','dkrak174',0);
insert into notice(NOTICE_NUM, CREATE_DATE, MODIFIED_DATE, NOTICE_CONTENTS, NOTICE_TITLE, MEMBER_ID, NOTICE_COUNT) values (26, now(),now(),'TestContents','Test26','tjdans174',0);


